.TH FBGRAB 1
.SH NAME
fbgrab \- take screenshots of the framebuffer
.SH SYNOPSIS
.B fbgrab
[
.B -iv
]
[
.B -b
.I bitdepth
]
[
.B -c|-C
.I console
]
[
.B -d
.I device
]
[
.B -f
.I file
]
[
.B -h
.I height
]
[
.B -s
.I seconds
]
[
.B -w
.I width
]
[
.B -z
.I level
]
.I file
.SH DESCRIPTION
.I fbgrab
reads the framebuffer device or a dump thereof and saves a PNG image file.
.SH OPTIONS
.PD 0
.TP \w'\fL-b\ \fIbitdepth\fPXX'u
.BI -b " bitdepth"
Specify the number of bits per pixel. This can be figured out automatically if
reading from a framebuffer device.
.TP
.BI -C " console"
Like
.BR -c ,
but wait some time before grabbing the virtual terminal.
.TP
.BI -c " console"
Grab a specific virtual terminal.
.TP
.BI -d " device"
Read the specified framebuffer device. If not given, the environment variable
.I FRAMEBUFFER
is used. If it does not exist, a default is used, typically
.IR /dev/fb0 .
.TP
.BI -f " file"
Read from
.I file
instead of from a device.
.BR -w ,
.BR -h ,
and
.B -b
must be used.
.TP
.BI -h " height"
Use specified height.
.TP
.B -i
Do ADAM7 interlacing.
.TP
.BI -s " seconds"
Wait before grabbing the screenshot. The virtual terminal can be switched
while waiting to grab a different virtual terminal.
.TP
.B -v
Be verbose.
.TP
.BI -w " width"
Use specified width.
.TP
.BI -z " level"
PNG compression level: 0 is fastest, 9 is best.
.PD
.SH TODO
Low-end bit depths, eg 1, 2, 4 & 8 bits.
.PP
Companion program
.B fbput
that would display a picture in the frambuffer.
.PP
Better utilization of the PNG-lib, all formats are first converted to 32
bitdepth and then stored as PNG\(emhardly the right approach.
.SH EXAMPLES
Take a screenshot and store it as
.IR fb.png :
.RS
fbgrab fb.png
.RE
.PP
Use a framebuffer dump:
.RS
cp /dev/fb0 dump
.br
fbgrab -w 1024 -h 768 -b 16 -f dump fb.png
.RE
.SH AUTHOR
Written by Gunnar Monell <gunnar.monell@gmail.com>.
Basically a rewrite of
.IR fbshot (1)
by Stephan Beyer <fbshot@s-beyer.de>.
.SH COPYRIGHT
Copyright \(co 2020 Humm <humm42@gmail.com>
.PP
Copyright \(co 2002-2020 Gunnar Monell <gunnar.monell@gmail.com>
.PP
Copyright \(co 2000 Stephan Beyer <fbshot@s-beyer.de>
.PP
This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; version 2.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
Street, Fifth Floor, Boston, MA  02110-1301, USA.
